#!/usr/bin/env -S node
import {
	Migration,
	MigrationCLI,
	addForeignKey,
	addUnique,
	col,
	createIndex,
	fn,
	lit,
	primaryKey,
} from "@prisma-next/postgres/migration";

export default class M extends Migration {
	override describe() {
		return {
			from: null,
			to: "sha256:e3b1f1cb255f8515a8bb97cbc5225bf8e6d19d3fb83c0b7ff72a6023927e2e59",
		};
	}

	override get operations() {
		return [
			this.createTable({
				schema: "public",
				table: "account",
				columns: [
					col("accessToken", "text"),
					col("accessTokenExpiresAt", "timestamptz"),
					col("accountId", "text", { notNull: true }),
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("id", "character(36)", { notNull: true }),
					col("idToken", "text"),
					col("password", "text"),
					col("providerId", "text", { notNull: true }),
					col("refreshToken", "text"),
					col("refreshTokenExpiresAt", "timestamptz"),
					col("scope", "text"),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("userId", "text", { notNull: true }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "literaryWork",
				columns: [
					col("averageTime", "int4"),
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("id", "character(36)", { notNull: true }),
					col("ongoing", "bool", { notNull: true, default: lit(true) }),
					col("releaseDate", "timestamptz"),
					col("synopsis", "jsonb"),
					col("tags", "jsonb", { notNull: true }),
					col("title", "jsonb", { notNull: true }),
					col("type", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "literaryWorkChapter",
				columns: [
					col("averageTime", "int4"),
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("id", "character(36)", { notNull: true }),
					col("number", "float8", { notNull: true }),
					col("pages", "int4"),
					col("releaseDate", "timestamptz"),
					col("sourceId", "text", { notNull: true }),
					col("title", "jsonb"),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "movie",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("duration", "int4"),
					col("id", "character(36)", { notNull: true }),
					col("releaseDate", "timestamptz"),
					col("title", "jsonb", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "session",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("expiresAt", "timestamptz", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("ipAddress", "text"),
					col("token", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("userAgent", "text"),
					col("userId", "text", { notNull: true }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "user",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("email", "text", { notNull: true }),
					col("emailVerified", "bool", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("image", "text"),
					col("name", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "userChapter",
				columns: [
					col("bookmarked", "bool", { notNull: true }),
					col("chapterId", "text", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("timeSpent", "int4"),
					col("userId", "text", { notNull: true }),
					col("when", "timestamptz"),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "userMovie",
				columns: [
					col("bookmarked", "bool", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("movieId", "text", { notNull: true }),
					col("progress", "int4"),
					col("rating", "float8"),
					col("userId", "text", { notNull: true }),
					col("when", "timestamptz"),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "userVideo",
				columns: [
					col("bookmarked", "bool", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("progress", "int4"),
					col("userId", "text", { notNull: true }),
					col("videoId", "text", { notNull: true }),
					col("when", "timestamptz"),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "userVideoGame",
				columns: [
					col("bookmarked", "bool", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("offset", "int4"),
					col("score", "float8"),
					col("timeSpent", "int4"),
					col("userId", "text", { notNull: true }),
					col("videoGameId", "text", { notNull: true }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "verification",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("expiresAt", "timestamptz", { notNull: true }),
					col("id", "character(36)", { notNull: true }),
					col("identifier", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("value", "text", { notNull: true }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "video",
				columns: [
					col("channelId", "text", { notNull: true }),
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("duration", "int4"),
					col("id", "character(36)", { notNull: true }),
					col("link", "text"),
					col("playlistId", "text"),
					col("releaseDate", "timestamptz"),
					col("title", "jsonb", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "videoChannel",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("externalId", "text"),
					col("id", "character(36)", { notNull: true }),
					col("link", "text"),
					col("name", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "videoGame",
				columns: [
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("id", "character(36)", { notNull: true }),
					col("releaseDate", "timestamptz"),
					col("title", "jsonb", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			this.createTable({
				schema: "public",
				table: "videoPlaylist",
				columns: [
					col("channelId", "text"),
					col("createdAt", "timestamptz", { notNull: true, default: fn("now()") }),
					col("id", "character(36)", { notNull: true }),
					col("link", "text"),
					col("title", "text", { notNull: true }),
					col("updatedAt", "timestamptz", { notNull: true, default: fn("now()") }),
				],
				constraints: [primaryKey(["id"])],
			}),
			addUnique("public", "literaryWorkChapter", "literaryWorkChapter_sourceId_number_key", [
				"sourceId",
				"number",
			]),
			addUnique("public", "session", "session_token_key", ["token"]),
			addUnique("public", "user", "user_email_key", ["email"]),
			addUnique("public", "userVideoGame", "userVideoGame_userId_videoGameId_key", ["userId", "videoGameId"]),
			createIndex("public", "account", "account_userId_idx", ["userId"]),
			createIndex("public", "literaryWorkChapter", "literaryWorkChapter_sourceId_idx", ["sourceId"]),
			createIndex("public", "session", "session_userId_idx", ["userId"]),
			createIndex("public", "userChapter", "userChapter_userId_idx", ["userId"]),
			createIndex("public", "userChapter", "userChapter_chapterId_idx", ["chapterId"]),
			createIndex("public", "userMovie", "userMovie_userId_idx", ["userId"]),
			createIndex("public", "userMovie", "userMovie_movieId_idx", ["movieId"]),
			createIndex("public", "userVideo", "userVideo_userId_idx", ["userId"]),
			createIndex("public", "userVideo", "userVideo_videoId_idx", ["videoId"]),
			createIndex("public", "userVideoGame", "userVideoGame_userId_idx", ["userId"]),
			createIndex("public", "userVideoGame", "userVideoGame_videoGameId_idx", ["videoGameId"]),
			createIndex("public", "video", "video_channelId_idx", ["channelId"]),
			createIndex("public", "video", "video_playlistId_idx", ["playlistId"]),
			createIndex("public", "videoPlaylist", "videoPlaylist_channelId_idx", ["channelId"]),
			addForeignKey("public", "account", {
				name: "account_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "literaryWorkChapter", {
				name: "literaryWorkChapter_sourceId_fkey",
				columns: ["sourceId"],
				references: { schema: "public", table: "literaryWork", columns: ["id"] },
			}),
			addForeignKey("public", "session", {
				name: "session_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "userChapter", {
				name: "userChapter_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "userChapter", {
				name: "userChapter_chapterId_fkey",
				columns: ["chapterId"],
				references: { schema: "public", table: "literaryWorkChapter", columns: ["id"] },
			}),
			addForeignKey("public", "userMovie", {
				name: "userMovie_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "userMovie", {
				name: "userMovie_movieId_fkey",
				columns: ["movieId"],
				references: { schema: "public", table: "movie", columns: ["id"] },
			}),
			addForeignKey("public", "userVideo", {
				name: "userVideo_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "userVideo", {
				name: "userVideo_videoId_fkey",
				columns: ["videoId"],
				references: { schema: "public", table: "video", columns: ["id"] },
			}),
			addForeignKey("public", "userVideoGame", {
				name: "userVideoGame_userId_fkey",
				columns: ["userId"],
				references: { schema: "public", table: "user", columns: ["id"] },
			}),
			addForeignKey("public", "userVideoGame", {
				name: "userVideoGame_videoGameId_fkey",
				columns: ["videoGameId"],
				references: { schema: "public", table: "videoGame", columns: ["id"] },
			}),
			addForeignKey("public", "video", {
				name: "video_channelId_fkey",
				columns: ["channelId"],
				references: { schema: "public", table: "videoChannel", columns: ["id"] },
			}),
			addForeignKey("public", "video", {
				name: "video_playlistId_fkey",
				columns: ["playlistId"],
				references: { schema: "public", table: "videoPlaylist", columns: ["id"] },
			}),
			addForeignKey("public", "videoPlaylist", {
				name: "videoPlaylist_channelId_fkey",
				columns: ["channelId"],
				references: { schema: "public", table: "videoChannel", columns: ["id"] },
			}),
		];
	}
}

MigrationCLI.run(import.meta.url, M);
